# Generated by Django 2.2 on 2019-04-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
