# Generated by Django 2.2 on 2019-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190430_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
