# Generated by Django 2.2 on 2019-05-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_followusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
