# Generated by Django 2.2 on 2019-05-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190509_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profession',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
