# Generated by Django 2.2 on 2019-05-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_notify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='userid',
        ),
    ]
