# Generated by Django 2.2 on 2019-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20190512_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
