# Generated by Django 2.2 on 2019-05-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='postcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('comment', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('aproved', models.BooleanField(default=False)),
                ('commenterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.register')),
            ],
        ),
    ]
