# Generated by Django 2.2 on 2019-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
