# Generated by Django 2.2 on 2019-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
